#define APP_ICON 102

// Launcher
#define DIAG_LAUNCHER 118

#define BTN_LAUNCHER_PLAY 1032
#define BTN_LAUNCHER_DISPLAY 1039
#define BTN_LAUNCHER_TROUBLESHOOT 1034
#define BTN_LAUNCHER_QUIT 1035
#define BTN_LAUNCHER_MPLAYER 1036
#define BTN_LAUNCHER_GAMESPY 1038
#define BTN_LAUNCHER_HEAT 1037

#define BMP_LAUNCHER_HEADER 125

#define BMP_LAUNCHER_QUIT_PRESSED 126
#define BMP_LAUNCHER_QUIT 127
#define BMP_LAUNCHER_PLAY 128
#define BMP_LAUNCHER_PLAY_PRESSED 129
#define BMP_LAUNCHER_DISPLAY 130
#define BMP_LAUNCHER_DISPLAY_PRESSED 131
#define BMP_LAUNCHER_TROUBLESHOOT 132
#define BMP_LAUNCHER_TROUBLESHOOT_PRESSED 133

#define BMP_LAUNCHER_MPLAYER 135
#define BMP_LAUNCHER_MPLAYER_PRESSED 136
#define BMP_LAUNCHER_GAMESPY 137
#define BMP_LAUNCHER_GAMESPY_PRESSED 138
#define BMP_LAUNCHER_HEAT 139
#define BMP_LAUNCHER_HEAT_PRESSED 140

// Settings Dialog
#define DIAG_SETTINGS 120

#define LST_SETTINGS_DISPLAY_DEVICE 1034
#define LST_SETTINGS_SCREEN_RESOLUTION 1036

#define BTN_SETTINGS_ADVANCED 1037
#define BTN_SETTINGS_DONE 1038

